apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: wangweifeng
  kubernetes.ops.region: shanghai
kind: Kustomization
namespace: easysoftware
resources:
- service.yaml
- deployment.yaml
- autoscaler.yaml
- ingress.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/easysoftware/easysoftware-monitoring-test
  newTag: master-b6006a
